import {
  describe,
  expect,
  test,
} from 'bun:test'

import {
  createSpacingRules,
} from './spacing'

describe('spacing tests', () => {
  test('creates spacing rules', () => {
    const result = createSpacingRules({
      sm: '8px',
      md: '16px',
      lg: '24px',
    })

    expect(result).toStrictEqual([
      ['top-sm', { top: '8px' }],
      ['right-sm', { right: '8px' }],
      ['bottom-sm', { bottom: '8px' }],
      ['left-sm', { left: '8px' }],
      ['inset-sm', { top: '8px', right: '8px', bottom: '8px', left: '8px' }],
      ['top-md', { top: '16px' }],
      ['right-md', { right: '16px' }],
      ['bottom-md', { bottom: '16px' }],
      ['left-md', { left: '16px' }],
      ['inset-md', { top: '16px', right: '16px', bottom: '16px', left: '16px' }],
      ['top-lg', { top: '24px' }],
      ['right-lg', { right: '24px' }],
      ['bottom-lg', { bottom: '24px' }],
      ['left-lg', { left: '24px' }],
      ['inset-lg', { top: '24px', right: '24px', bottom: '24px', left: '24px' }],
      ['m-auto', { margin: 'auto' }],
      ['mt-auto', { 'margin-top': 'auto' }],
      ['mb-auto', { 'margin-bottom': 'auto' }],
      ['ml-auto', { 'margin-left': 'auto' }],
      ['mr-auto', { 'margin-right': 'auto' }],
      ['mx-auto', { 'margin-left': 'auto', 'margin-right': 'auto' }],
      ['my-auto', { 'margin-top': 'auto', 'margin-bottom': 'auto' }],
      ['m-sm', { margin: '8px' }],
      ['mt-sm', { 'margin-top': '8px' }],
      ['mb-sm', { 'margin-bottom': '8px' }],
      ['ml-sm', { 'margin-left': '8px' }],
      ['mr-sm', { 'margin-right': '8px' }],
      ['mx-sm', { 'margin-left': '8px', 'margin-right': '8px' }],
      ['my-sm', { 'margin-top': '8px', 'margin-bottom': '8px' }],
      ['p-sm', { padding: '8px' }],
      ['pt-sm', { 'padding-top': '8px' }],
      ['pb-sm', { 'padding-bottom': '8px' }],
      ['pl-sm', { 'padding-left': '8px' }],
      ['pr-sm', { 'padding-right': '8px' }],
      ['px-sm', { 'padding-left': '8px', 'padding-right': '8px' }],
      ['py-sm', { 'padding-top': '8px', 'padding-bottom': '8px' }],
      ['gap-sm', { gap: '8px' }],
      ['gap-x-sm', { 'column-gap': '8px' }],
      ['gap-y-sm', { 'row-gap': '8px' }],
      ['m-md', { margin: '16px' }],
      ['mt-md', { 'margin-top': '16px' }],
      ['mb-md', { 'margin-bottom': '16px' }],
      ['ml-md', { 'margin-left': '16px' }],
      ['mr-md', { 'margin-right': '16px' }],
      ['mx-md', { 'margin-left': '16px', 'margin-right': '16px' }],
      ['my-md', { 'margin-top': '16px', 'margin-bottom': '16px' }],
      ['p-md', { padding: '16px' }],
      ['pt-md', { 'padding-top': '16px' }],
      ['pb-md', { 'padding-bottom': '16px' }],
      ['pl-md', { 'padding-left': '16px' }],
      ['pr-md', { 'padding-right': '16px' }],
      ['px-md', { 'padding-left': '16px', 'padding-right': '16px' }],
      ['py-md', { 'padding-top': '16px', 'padding-bottom': '16px' }],
      ['gap-md', { gap: '16px' }],
      ['gap-x-md', { 'column-gap': '16px' }],
      ['gap-y-md', { 'row-gap': '16px' }],
      ['m-lg', { margin: '24px' }],
      ['mt-lg', { 'margin-top': '24px' }],
      ['mb-lg', { 'margin-bottom': '24px' }],
      ['ml-lg', { 'margin-left': '24px' }],
      ['mr-lg', { 'margin-right': '24px' }],
      ['mx-lg', { 'margin-left': '24px', 'margin-right': '24px' }],
      ['my-lg', { 'margin-top': '24px', 'margin-bottom': '24px' }],
      ['p-lg', { padding: '24px' }],
      ['pt-lg', { 'padding-top': '24px' }],
      ['pb-lg', { 'padding-bottom': '24px' }],
      ['pl-lg', { 'padding-left': '24px' }],
      ['pr-lg', { 'padding-right': '24px' }],
      ['px-lg', { 'padding-left': '24px', 'padding-right': '24px' }],
      ['py-lg', { 'padding-top': '24px', 'padding-bottom': '24px' }],
      ['gap-lg', { gap: '24px' }],
      ['gap-x-lg', { 'column-gap': '24px' }],
      ['gap-y-lg', { 'row-gap': '24px' }],
    ])
  })
})
